version: "3"
services:
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    command: -c 'max_prepared_transactions=20' -c 'max_connections=100000'
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - db
    links:
      - "db:db"
